"""Add created_at and due_date

Revision ID: 0dd380ce4664
Revises: a056f9990bf8
Create Date: 2025-05-27 13:42:06.674581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd380ce4664'
down_revision: Union[str, None] = 'a056f9990bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('todos', sa.Column('plan_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'plan_date')
    op.drop_column('todos', 'created')
    # ### end Alembic commands ###
